DROP TABLE IF EXISTS saes_testimonies;
DROP TABLE IF EXISTS saes_news;
DROP TABLE IF EXISTS saes_promos;
DROP TABLE IF EXISTS user_reviews;
DROP TABLE IF EXISTS user_purchases;
DROP TABLE IF EXISTS saes_programs;
DROP TABLE IF EXISTS saes_items;
DROP TABLE IF EXISTS saes_users;

DROP TYPE IF EXISTS item_type;

CREATE TYPE item_type AS ENUM (
    'Programs',
    'Apparel',
    'Equipment'
);

CREATE TABLE saes_users (
    id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    photo VARCHAR(2000),
    name TEXT NOT NULL,
    user_name TEXT NOT NULL UNIQUE,
    password TEXT NOT NULL,
    email TEXT NOT NULL,
    address TEXT NOT NULL,
    state TEXT NOT NULL,
    zip INTEGER NOT NULL,
    isAdmin BOOLEAN NOT NULL
);

CREATE TABLE saes_items (
    id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    title TEXT NOT NULL,
    price TEXT NOT NULL,
    category item_type NOT NULL,
    description TEXT NOT NULL,
    date_created TIMESTAMPTZ DEFAULT now() NOT NULL
);

CREATE TABLE saes_programs (
    id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    title TEXT NOT NULL,
    price TEXT NOT NULL,
    description TEXT NOT NULL,
    date_created TIMESTAMPTZ DEFAULT now() NOT NULL
);

CREATE TABLE user_purchases (
    id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    title TEXT NOT NULL,
    price TEXT NOT NULL,
    category item_type NOT NULL,
    userId INTEGER REFERENCES saes_users(id) ON DELETE CASCADE NULL,
    itemId INTEGER REFERENCES saes_items(id) ON DELETE CASCADE NULL,
    programId INTEGER REFERENCES saes_programs(id) ON DELETE CASCADE NULL
);

CREATE TABLE user_reviews (
    id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    content TEXT NOT NULL,
    rating INTEGER NOT NULL,
    date_created TIMESTAMPTZ DEFAULT now() NOT NULL,
    programId INTEGER REFERENCES saes_programs(id) ON DELETE CASCADE NULL,
    itemId INTEGER REFERENCES saes_items(id) ON DELETE CASCADE NULL,
    userId INTEGER REFERENCES saes_users(id) ON DELETE CASCADE NULL
);

CREATE TABLE saes_promos (
    id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    content TEXT NOT NULL,
    date_created TIMESTAMPTZ DEFAULT now() NOT NULL
);

CREATE TABLE saes_news (
    id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    content TEXT NOT NULL,
    date_created TIMESTAMPTZ DEFAULT now() NOT NULL
);

CREATE TABLE saes_testimonies (
    id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    photo VARCHAR(2000),
    content TEXT NOT NULL,
    date_created TIMESTAMPTZ DEFAULT now() NOT NULL
);